name: Chat-App Deployment
on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build & Deploy
    # Le serveur distant est entièrement configuré et géré par moi-même
    runs-on: self-hosted
    steps:
      # Accès au dépôt Github
      - name: Checking Github repository access
        uses: actions/checkout@master

      # Installation de Node.JS
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      # Mise à jour des dépendances Ubuntu
      - name: Update server packages
        run: sudo apt-get update

      # Installation des dépendances
      - name: Install npm dependencies
        run: cd backend && npm install
        run: cd ../frontend && npm install
        run: cd ..

      # Lancement de l'application
      - name: Build Chat-App
        run: cd frontend && npm run build
        run: cp -r build/* /var/www/chat-app && cd ..
        run: cd backend && pm2 restart backend-server